### ISSUE TITLE
全部安好运行后，在网页点击搜索报错

### ISSUE THREAD

**Issue by liuyizhuo11235** [Faker-lz/Topic_and_user_profile_analysis_system#11]
大佬，当在前端网页点击搜索按钮时，爬虫报错
Traceback (most recent call last):
File "C:\Users\hl199\Topic_and_user_profile_analysis_system-master\code\weibo_crawler\selector_parser\search_weibo_parser.py", line 22, in parse_page
weibo_list = self._get_all_weibo()
File "C:\Users\hl199\Topic_and_user_profile_analysis_system-master\code\weibo_crawler\selector_parser\search_weibo_parser.py", line 33, in _get_all_weibo
for weibo in self._parse_weibo():
File "C:\Users\hl199\Topic_and_user_profile_analysis_system-master\code\weibo_crawler\selector_parser\search_weibo_parser.py", line 55, in _parse_weibo
weibo['weibo_id'] = sel.xpath('(.//p[@Class="from"])[last()]/a[1]/@href')[0].split('/')[-1].split('?')[0]
IndexError: list index out of range
似乎是微博没有返回任何东西，是我爬虫配置出错了吗？
        同时main.py报错pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
       请问该怎么解决？

**Comment by liuyizhuo11235** [comment]
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [WinError 10061] 这个问题解决了，安装一个MongoDB就行（大佬应该在文档里面提一下呀）
但前面这个错误扔无法解决，感觉是爬虫proxy的设置问题。我能直接用你代码里面自带的proxy吗？还是需要另外设置proxy服务器？

**Comment by liuyizhuo11235** [comment]
不使用代理就是把proxy设为127.0.0.1吗？

**Comment by Faker-lz** [comment]
设置成127.0.0.1再加端口就行

**Comment by allurelzh** [comment]
我也遇到了这个问题，请问是怎么解决的？

**Comment by Lurkhunter** [comment]
> 我也遇到了这个问题，请问是怎么解决的？

uu想问一下，后端访问根路由一直404 not found 怎么解决呢
